package com.metallum.render.metal3;

import com.metallum.mtl.MTLCompareFunction;
import com.metallum.mtl.MTLPixelFormat;
import com.metallum.mtl.MTLPrimitiveType;
import com.metallum.mtl.metal3.MTLRenderCommandEncoder;
import com.metallum.mtl.MTLRenderPipelineDescriptor;
import com.metallum.mtl.MTLSamplerAddressMode;
import com.metallum.mtl.MTLSamplerDescriptor;
import com.metallum.mtl.MTLSamplerMinMagFilter;
import com.metallum.mtl.MTLSamplerMipFilter;
import com.metallum.objc.ObjC;
import com.mojang.blaze3d.GpuFormat;
import com.mojang.blaze3d.textures.GpuTexture;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import org.joml.Vector4fc;

import java.lang.foreign.MemorySegment;
import com.metallum.render.shared.MetalGpuTexture;
import com.metallum.render.shared.MetalGpuTextureView;
import com.metallum.render.MetalDevice;

/**
 * Optional-backend bridge for depth textures whose mip chain cannot be generated by Metal's
 * native color mipmap command.
 * <p>
 * This class knows only the generic GPU contract: a D32_FLOAT 2D texture with multiple levels is
 * reduced progressively from level {@code n - 1} into level {@code n} using nearest filtering.
 * Shader-pack target names and scheduling stay outside Metallum.
 */
@Environment(EnvType.CLIENT)
public final class Metal3DepthMipmapBridge {
    private static final String DEPTH_MIP_MSL = """
            #include <metal_stdlib>
            using namespace metal;

            struct DepthMipVertexOut {
              float4 position [[position]];
              float2 uv;
            };

            struct DepthMipFragmentOut {
              float depth [[depth(any)]];
            };

            vertex DepthMipVertexOut metallum_depth_mip_vs(uint vertexId [[vertex_id]]) {
              const float2 positions[3] = {
                float2(-1.0,  1.0),
                float2( 3.0,  1.0),
                float2(-1.0, -3.0)
              };
              const float2 uvs[3] = {
                float2(0.0, 0.0),
                float2(2.0, 0.0),
                float2(0.0, 2.0)
              };

              DepthMipVertexOut out;
              out.position = float4(positions[vertexId], 0.0, 1.0);
              out.uv = uvs[vertexId];
              return out;
            }

            fragment DepthMipFragmentOut metallum_depth_mip_fs(
              DepthMipVertexOut in [[stage_in]],
              depth2d<float> source [[texture(0)]],
              sampler nearestSampler [[sampler(0)]]
            ) {
              DepthMipFragmentOut out;
              out.depth = source.sample(nearestSampler, in.uv);
              return out;
            }
            """;

    private Metal3DepthMipmapBridge() {
    }

    /**
     * Generates a progressive nearest mip chain for a D32_FLOAT Metal texture.
     *
     * @param encoderBackend a Metallum {@code MetalCommandEncoder}, typed as {@link Object} for
     *                       optional clients
     * @return true when every level after zero was encoded, false when the generic depth path does
     *         not apply to this texture/backend
     */
    public static boolean generate(final Object encoderBackend, final GpuTexture texture) {
        if (!(encoderBackend instanceof MetalCommandEncoder encoder)
                || !(texture instanceof MetalGpuTexture metalTexture)
                || texture.isClosed()
                || texture.getFormat() != GpuFormat.D32_FLOAT
                || texture.getMipLevels() <= 1
                || texture.getDepthOrLayers() != 1
                || (texture.usage() & GpuTexture.USAGE_TEXTURE_BINDING) == 0
                || (texture.usage() & GpuTexture.USAGE_RENDER_ATTACHMENT) == 0) {
            return false;
        }

        encoder.flushPendingClear(metalTexture);

        MetalDevice device = metalTexture.device();
        Metal3ExecutionState metal3 = encoder.executionState();

        MemorySegment vertexFunction = metal3.getOrCompileFunction(DEPTH_MIP_MSL, "metallum_depth_mip_vs");
        MemorySegment fragmentFunction = metal3.getOrCompileFunction(DEPTH_MIP_MSL, "metallum_depth_mip_fs");
        if (ObjC.isNil(vertexFunction) || ObjC.isNil(fragmentFunction)) {
            return false;
        }

        MemorySegment pipeline;
        try (MTLRenderPipelineDescriptor descriptor = new MTLRenderPipelineDescriptor()) {
            descriptor.setCompiledFunctions(vertexFunction, fragmentFunction);
            descriptor.setDepthStencilFormats(MTLPixelFormat.Depth32Float, MTLPixelFormat.Invalid);
            pipeline = device.metalDevice().newRenderPipelineState(descriptor);
        }
        if (ObjC.isNil(pipeline)) {
            return false;
        }

        MemorySegment nearestSampler;
        try (MTLSamplerDescriptor descriptor = MTLSamplerDescriptor.create()) {
            descriptor.minFilter(MTLSamplerMinMagFilter.Nearest);
            descriptor.magFilter(MTLSamplerMinMagFilter.Nearest);
            descriptor.mipFilter(MTLSamplerMipFilter.NotMipmapped);
            descriptor.sAddressMode(MTLSamplerAddressMode.ClampToEdge);
            descriptor.tAddressMode(MTLSamplerAddressMode.ClampToEdge);
            nearestSampler = device.metalDevice().newSamplerState(descriptor);
        } catch (RuntimeException | Error e) {
            encoder.queueForDestroy(() -> ObjC.release(pipeline));
            throw e;
        }
        if (ObjC.isNil(nearestSampler)) {
            encoder.queueForDestroy(() -> ObjC.release(pipeline));
            return false;
        }

        MemorySegment depthState = metal3.depthStencilState(MTLCompareFunction.Always, true);
        try {
            for (int level = 1; level < texture.getMipLevels(); level++) {
                MetalGpuTextureView source = new MetalGpuTextureView(texture, level - 1, 1);
                MetalGpuTextureView destination = new MetalGpuTextureView(texture, level, 1);
                try {
                    int width = Math.max(1, texture.getWidth(level));
                    int height = Math.max(1, texture.getHeight(level));
                    MTLRenderCommandEncoder render = encoder.renderCommandEncoder(
                            new MetalGpuTextureView[0],
                            destination,
                            width,
                            height,
                            new Vector4fc[0],
                            null,
                            null
                    );
                    render.setRenderPipelineState(pipeline);
                    render.setDepthStencilState(depthState);
                    render.setFragmentTexture(source.nativeHandle(), 0L);
                    render.setFragmentSamplerState(nearestSampler, 0L);
                    render.drawPrimitives(MTLPrimitiveType.Triangle, 0, 3, 1, 0);

                    // The texture uses untracked hazards. Ending every level updates the encoder's
                    // global fence, and the next level's render encoder waits on that fence before
                    // sampling the level just written.
                    encoder.endEncoder();
                } finally {
                    destination.close();
                    source.close();
                }
            }
            return true;
        } finally {
            encoder.queueForDestroy(() -> ObjC.release(nearestSampler));
            encoder.queueForDestroy(() -> ObjC.release(pipeline));
        }
    }
}
